name: Release

on:
  push:
    branches:
      - release

env:
  CI: true

jobs:
  release:
    name: Build, Release & Publish
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        with:
          main-branch-name: 'release'
        uses: nrwl/nx-set-shas@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure CI Git User
        run: |
          git config --global user.name 'dubemarcantoine'
          git config --global user.email 'madube94@gmail.com'
          git remote set-url origin https://dubemarcantoine:$GITHUB_TOKEN@github.com/dubemarcantoine/nx-dev-tools
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Build projects
        run: |
          npm run affected:build

      - name: Build, Release on GitHub & Publish to NPM
        env:
          HUSKY: '0'
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run affected:release
